# Update Logs
## 2020.12.20
#### Updated terms
- Rename the main program file `bert_BiLSTM-CRF.ipynb` to 
`bertNER.ipynb`.
- 模型儲存與載入路徑一律由變數 `MODEL_SAVE_DIR` 指定
- NERAcceptanceCallback的預設參數 `mode='max'` 改為 `mode='auto'`

#### Pull terms
- bertNER.ipynb
- model_acceptance_callback.py
- albertNER.ipynb & robertaNER.ipynb 如果你需要的話

# Setup the workspace
Here is for google colab.

In [1]:
import os
from google.colab import drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
os.chdir("/content/drive/MyDrive/AICUP2020/")

# Prepare Environments

In [4]:
!pip install kashgari>=2.0.0 &> /dev/null
from datetime import datetime
from configparser import ConfigParser
import re
import numpy as np
import pandas as pd
import tensorflow as tf

import kashgari
from kashgari.embeddings import BertEmbedding, TransformerEmbedding
from embedding_model import AlbertEmbedding, RoBertaEmbedding
from bilstm_crf_model import BiLSTM_CRF_Model, DoubleBiLSTM_CRF_Model
from bigru_crf_model import BiGRU_CRF_Model
from model_acceptance_callback import NERAcceptanceCallBack

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from utils import load_test_file, format_result, split_chunks, save_model, load_model
from data_generator import read_data, generate_dataset

In [5]:
# Define const
MODEL_SAVE_DIR = 'model/'

# Get config
config = ConfigParser()
config.read('config.ini')
LSTM_UNITS = int(config['MODEL']['lstm_units'])
DROPOUT = float(config['MODEL']['dropout'])
EPOCHS = int(config['TRAIN']['epochs'])
BATCH_SIZE = int(config['TRAIN']['batch_size'])
PREDICT_BATCH_SIZE = int(config['PREDICT']['batch_size'])

# Read Training Data

In [6]:
# x is a list of characters, e.g ['你', '好', '嗎', ...]
# y is a list of labels of each characters, e.g ['O', 'O', 'O', ...]
training_data = read_data(['data/TRAIN_FINAL'], end_flag='')
train_x = list(map(lambda x: [wl[0] for wl in x], training_data))
train_y = list(map(lambda x: [wl[1] for wl in x], training_data))

validation_data = read_data(['data/TEST_FINAL'], end_flag='')
valid_x = list(map(lambda x: [wl[0] for wl in x], validation_data))
valid_y = list(map(lambda x: [wl[1] for wl in x], validation_data))

In [7]:
train_x_chunks = []
for article in train_x:
  article_chunks = split_chunks(article)
  train_x_chunks.extend(article_chunks)

train_y_chunks = []
for article in train_y:
  article_chunks = split_chunks(article)
  train_y_chunks.extend(article_chunks)

valid_x_chunks = []
for article in valid_x:
  article_chunks = split_chunks(article)
  valid_x_chunks.extend(article_chunks)

valid_y_chunks = []
for article in valid_y:
  article_chunks = split_chunks(article)
  valid_y_chunks.extend(article_chunks)

# Build Model

In [8]:
# Bert + BiLSTM-CRF
hyper_parameters = {
  'layer_blstm': {
    'units': LSTM_UNITS,
    'return_sequences': True
  },
  'layer_dropout': {
    'rate': DROPOUT
  },
  'layer_time_distributed': {

  },
  'layer_activation': {
    'activation': 'softmax'
  }
}
bert_embed = BertEmbedding('chinese_L-12_H-768_A-12/')
model = BiLSTM_CRF_Model(bert_embed, hyper_parameters=hyper_parameters)

2020-12-31 13:14:06,103 [DEBUG] kashgari - ------------------------------------------------
2020-12-31 13:14:06,104 [DEBUG] kashgari - Loaded transformer model's vocab
2020-12-31 13:14:06,106 [DEBUG] kashgari - config_path       : chinese_L-12_H-768_A-12/bert_config.json
2020-12-31 13:14:06,108 [DEBUG] kashgari - vocab_path      : chinese_L-12_H-768_A-12/vocab.txt
2020-12-31 13:14:06,109 [DEBUG] kashgari - checkpoint_path : chinese_L-12_H-768_A-12/bert_model.ckpt
2020-12-31 13:14:06,110 [DEBUG] kashgari - Top 50 words    : ['[PAD]', '[unused1]', '[unused2]', '[unused3]', '[unused4]', '[unused5]', '[unused6]', '[unused7]', '[unused8]', '[unused9]', '[unused10]', '[unused11]', '[unused12]', '[unused13]', '[unused14]', '[unused15]', '[unused16]', '[unused17]', '[unused18]', '[unused19]', '[unused20]', '[unused21]', '[unused22]', '[unused23]', '[unused24]', '[unused25]', '[unused26]', '[unused27]', '[unused28]', '[unused29]', '[unused30]', '[unused31]', '[unused32]', '[unused33]', '[unused

# Load Model

In [ ]:
# load model
# model, model_info = load_model(f'{MODEL_SAVE_DIR}/', BiLSTM_CRF_Model)
# model.crf_layer = model.layer_crf
# model.compile_model()
# if model_info is not None:
#   start_epoch = model_info['epoch']
#   monitor = model_info['monitor']
#   threshold = model_info['best']
# else:
#   start_epoch = 0
#   threshold = -np.Inf

# print(f'epoch: {start_epoch}\nmonitor: {monitor}\nbest: {threshold}')

# Train Model

In [12]:
# for loaded model
# ner_cb = NERAcceptanceCallBack(f'{MODEL_SAVE_DIR}/', 
#                 kash_model=model, 
#                 validate_data_x=valid_x_chunks, 
#                 validate_data_y=valid_y_chunks,
#                 monitor='f1-score',
#                 threshold=threshold,
#                 history_record_mode='keep')
# history = model.fit(train_x_chunks,
#            train_y_chunks,
#            x_validate=valid_x_chunks,
#            y_validate=valid_y_chunks,
#            epochs=start_epoch + EPOCHS,
#            batch_size=BATCH_SIZE,
#            callbacks=[ner_cb], 
#            fit_kwargs={'initial_epoch': start_epoch})

# for initial-built model
ner_cb = NERAcceptanceCallBack(f'{MODEL_SAVE_DIR}/', 
                kash_model=model,
                validate_data_x=valid_x_chunks,
                validate_data_y=valid_y_chunks,
                monitor='f1-score',
                history_record_mode='new')
history = model.fit(train_x_chunks,
           train_y_chunks,
           x_validate=valid_x_chunks,
           y_validate=valid_y_chunks,
           epochs=10,
           batch_size=BATCH_SIZE,
           callbacks=[ner_cb])

Preparing text vocab dict: 100%|██████████| 200/200 [00:00<00:00, 9175.90it/s]
2020-12-31 13:14:49,203 [DEBUG] kashgari - --- Build vocab dict finished, Total: 1648 ---
2020-12-31 13:14:49,204 [DEBUG] kashgari - Top-10: ['[PAD]', '[UNK]', '[CLS]', '[SEP]', '：', '。', '，', '師', '是', '民']
Preparing text vocab dict: 100%|██████████| 200/200 [00:00<00:00, 14002.95it/s]
2020-12-31 13:14:49,274 [DEBUG] kashgari - --- Build vocab dict finished, Total: 28 ---
2020-12-31 13:14:49,275 [DEBUG] kashgari - Top-10: ['[PAD]', 'O', 'I-time', 'B-time', 'I-med_exam', 'I-name', 'B-med_exam', 'I-location', 'I-money', 'B-name']
Calculating sequence length: 100%|██████████| 200/200 [00:00<00:00, 93403.94it/s]
2020-12-31 13:15:36,561 [DEBUG] kashgari - Calculated sequence length = 511
2020-12-31 13:15:38,945 [DEBUG] kashgari - fit input shape: (2, 128, 511)
2020-12-31 13:15:38,946 [DEBUG] kashgari - fit input shape: (128, 511)


Epoch 1/10
5/5 [==============================] - 71s 10s/step - loss: 750.1139 - accuracy: 0.5566 - val_loss: 1019.9357 - val_accuracy: 0.9754


2020-12-31 13:16:49,740 [DEBUG] kashgari - predict seq_length: None, input: (2, 200, 512)




13/13 [==============================] - 18s 982ms/step


2020-12-31 13:17:07,653 [DEBUG] kashgari - predict output: (200, 512)
2020-12-31 13:17:07,654 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
2020-12-31 13:17:08,366 [INFO] kashgari - Successfully recorded this epoch into model///history/history_0.csv
2020-12-31 13:17:08,367 [INFO] kashgari - Epoch 1: f1-score improved from -inf to 0.00000, saving model to model//



                precision    recall  f1-score   support

      location     0.0000    0.0000    0.0000        53
          time     0.0000    0.0000    0.0000       450
       contact     0.0000    0.0000    0.0000        13
      med_exam     0.0000    0.0000    0.0000        84
         money     0.0000    0.0000    0.0000        11
          name     0.0000    0.0000    0.0000        43
        family     0.0000    0.0000    0.0000        11
    profession     0.0000    0.0000    0.0000        11
clinical_event     0.0000    0.0000    0.0000         2
     education     0.0000    0.0000    0.0000         1

     micro avg     0.0000    0.0000    0.0000       679
     macro avg     0.0000    0.0000    0.0000       679

epoch: 0 precision: 0.000000, recall: 0.000000, f1-score: 0.000000


2020-12-31 13:17:11,868 [INFO] kashgari - model saved to /content/drive/My Drive/AICUP2020/model


Epoch 2/10
5/5 [==============================] - 43s 9s/step - loss: 131.0843 - accuracy: 0.9654 - val_loss: 1009.3759 - val_accuracy: 0.9729


2020-12-31 13:17:54,449 [DEBUG] kashgari - predict seq_length: None, input: (2, 200, 512)




13/13 [==============================] - 12s 957ms/step


2020-12-31 13:18:07,012 [DEBUG] kashgari - predict output: (200, 512)
2020-12-31 13:18:07,014 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
2020-12-31 13:18:07,709 [INFO] kashgari - Successfully recorded this epoch into model///history/history_0.csv
2020-12-31 13:18:07,710 [INFO] kashgari - Epoch 2: f1-score did not improve from 0.00000



                precision    recall  f1-score   support

      location     0.0000    0.0000    0.0000        53
          time     0.0000    0.0000    0.0000       450
       contact     0.0000    0.0000    0.0000        13
      med_exam     0.0000    0.0000    0.0000        84
         money     0.0000    0.0000    0.0000        11
          name     0.0000    0.0000    0.0000        43
        family     0.0000    0.0000    0.0000        11
    profession     0.0000    0.0000    0.0000        11
clinical_event     0.0000    0.0000    0.0000         2
     education     0.0000    0.0000    0.0000         1

     micro avg     0.0000    0.0000    0.0000       679
     macro avg     0.0000    0.0000    0.0000       679

epoch: 1 precision: 0.000000, recall: 0.000000, f1-score: 0.000000
Epoch 3/10
5/5 [==============================] - 41s 8s/step - loss: 94.7196 - accuracy: 0.9667 - val_loss: 1038.0022 - val_accuracy: 0.9785


2020-12-31 13:18:48,810 [DEBUG] kashgari - predict seq_length: None, input: (2, 200, 512)




13/13 [==============================] - 13s 991ms/step


2020-12-31 13:19:01,767 [DEBUG] kashgari - predict output: (200, 512)
2020-12-31 13:19:01,769 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
2020-12-31 13:19:02,445 [INFO] kashgari - Successfully recorded this epoch into model///history/history_0.csv
2020-12-31 13:19:02,446 [INFO] kashgari - Epoch 3: f1-score did not improve from 0.00000



                precision    recall  f1-score   support

      location     0.0000    0.0000    0.0000        53
          time     0.0000    0.0000    0.0000       450
       contact     0.0000    0.0000    0.0000        13
      med_exam     0.0000    0.0000    0.0000        84
         money     0.0000    0.0000    0.0000        11
          name     0.0000    0.0000    0.0000        43
        family     0.0000    0.0000    0.0000        11
    profession     0.0000    0.0000    0.0000        11
clinical_event     0.0000    0.0000    0.0000         2
     education     0.0000    0.0000    0.0000         1

     micro avg     0.0000    0.0000    0.0000       679
     macro avg     0.0000    0.0000    0.0000       679

epoch: 2 precision: 0.000000, recall: 0.000000, f1-score: 0.000000
Epoch 4/10
5/5 [==============================] - 41s 8s/step - loss: 72.6401 - accuracy: 0.9682 - val_loss: 1047.9662 - val_accuracy: 0.9753


2020-12-31 13:19:43,594 [DEBUG] kashgari - predict seq_length: None, input: (2, 200, 512)




13/13 [==============================] - 12s 949ms/step


2020-12-31 13:19:56,056 [DEBUG] kashgari - predict output: (200, 512)
2020-12-31 13:19:56,057 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
2020-12-31 13:19:56,717 [INFO] kashgari - Successfully recorded this epoch into model///history/history_0.csv
2020-12-31 13:19:56,718 [INFO] kashgari - Epoch 4: f1-score did not improve from 0.00000



                precision    recall  f1-score   support

      location     0.0000    0.0000    0.0000        53
          time     0.0000    0.0000    0.0000       450
       contact     0.0000    0.0000    0.0000        13
      med_exam     0.0000    0.0000    0.0000        84
         money     0.0000    0.0000    0.0000        11
          name     0.0000    0.0000    0.0000        43
        family     0.0000    0.0000    0.0000        11
    profession     0.0000    0.0000    0.0000        11
clinical_event     0.0000    0.0000    0.0000         2
     education     0.0000    0.0000    0.0000         1

     micro avg     0.0000    0.0000    0.0000       679
     macro avg     0.0000    0.0000    0.0000       679

epoch: 3 precision: 0.000000, recall: 0.000000, f1-score: 0.000000
Epoch 5/10
5/5 [==============================] - 41s 8s/step - loss: 73.9916 - accuracy: 0.9655 - val_loss: 1007.6442 - val_accuracy: 0.9745


2020-12-31 13:20:37,986 [DEBUG] kashgari - predict seq_length: None, input: (2, 200, 512)




13/13 [==============================] - 13s 952ms/step


2020-12-31 13:20:50,562 [DEBUG] kashgari - predict output: (200, 512)
2020-12-31 13:20:50,563 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
2020-12-31 13:20:51,230 [INFO] kashgari - Successfully recorded this epoch into model///history/history_0.csv
2020-12-31 13:20:51,231 [INFO] kashgari - Epoch 5: f1-score did not improve from 0.00000



                precision    recall  f1-score   support

      location     0.0000    0.0000    0.0000        53
          time     0.0000    0.0000    0.0000       450
       contact     0.0000    0.0000    0.0000        13
      med_exam     0.0000    0.0000    0.0000        84
         money     0.0000    0.0000    0.0000        11
          name     0.0000    0.0000    0.0000        43
        family     0.0000    0.0000    0.0000        11
    profession     0.0000    0.0000    0.0000        11
clinical_event     0.0000    0.0000    0.0000         2
     education     0.0000    0.0000    0.0000         1

     micro avg     0.0000    0.0000    0.0000       679
     macro avg     0.0000    0.0000    0.0000       679

epoch: 4 precision: 0.000000, recall: 0.000000, f1-score: 0.000000
Epoch 6/10
5/5 [==============================] - 41s 8s/step - loss: 65.7861 - accuracy: 0.9672 - val_loss: 1024.4453 - val_accuracy: 0.9763


2020-12-31 13:21:32,282 [DEBUG] kashgari - predict seq_length: None, input: (2, 200, 512)




13/13 [==============================] - 13s 973ms/step


2020-12-31 13:21:45,058 [DEBUG] kashgari - predict output: (200, 512)
2020-12-31 13:21:45,059 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
2020-12-31 13:21:45,726 [INFO] kashgari - Successfully recorded this epoch into model///history/history_0.csv
2020-12-31 13:21:45,727 [INFO] kashgari - Epoch 6: f1-score did not improve from 0.00000



                precision    recall  f1-score   support

      location     0.0000    0.0000    0.0000        53
          time     0.0000    0.0000    0.0000       450
       contact     0.0000    0.0000    0.0000        13
      med_exam     0.0000    0.0000    0.0000        84
         money     0.0000    0.0000    0.0000        11
          name     0.0000    0.0000    0.0000        43
        family     0.0000    0.0000    0.0000        11
    profession     0.0000    0.0000    0.0000        11
clinical_event     0.0000    0.0000    0.0000         2
     education     0.0000    0.0000    0.0000         1

     micro avg     0.0000    0.0000    0.0000       679
     macro avg     0.0000    0.0000    0.0000       679

epoch: 5 precision: 0.000000, recall: 0.000000, f1-score: 0.000000
Epoch 7/10
5/5 [==============================] - 43s 9s/step - loss: 59.8907 - accuracy: 0.9665 - val_loss: 1052.8760 - val_accuracy: 0.9746


2020-12-31 13:22:28,948 [DEBUG] kashgari - predict seq_length: None, input: (2, 200, 512)




13/13 [==============================] - 13s 979ms/step


2020-12-31 13:22:41,729 [DEBUG] kashgari - predict output: (200, 512)
2020-12-31 13:22:41,730 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
2020-12-31 13:22:42,387 [INFO] kashgari - Successfully recorded this epoch into model///history/history_0.csv
2020-12-31 13:22:42,390 [INFO] kashgari - Epoch 7: f1-score did not improve from 0.00000



                precision    recall  f1-score   support

      location     0.0000    0.0000    0.0000        53
          time     0.0000    0.0000    0.0000       450
       contact     0.0000    0.0000    0.0000        13
      med_exam     0.0000    0.0000    0.0000        84
         money     0.0000    0.0000    0.0000        11
          name     0.0000    0.0000    0.0000        43
        family     0.0000    0.0000    0.0000        11
    profession     0.0000    0.0000    0.0000        11
clinical_event     0.0000    0.0000    0.0000         2
     education     0.0000    0.0000    0.0000         1

     micro avg     0.0000    0.0000    0.0000       679
     macro avg     0.0000    0.0000    0.0000       679

epoch: 6 precision: 0.000000, recall: 0.000000, f1-score: 0.000000
Epoch 8/10
5/5 [==============================] - 41s 9s/step - loss: 52.7721 - accuracy: 0.9694 - val_loss: 1023.4812 - val_accuracy: 0.9764


2020-12-31 13:23:23,666 [DEBUG] kashgari - predict seq_length: None, input: (2, 200, 512)




13/13 [==============================] - 12s 955ms/step


2020-12-31 13:23:36,183 [DEBUG] kashgari - predict output: (200, 512)
2020-12-31 13:23:36,184 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 2 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:23:36,842 [INFO] kashgari - Successfully recorded this epoch into model///history/history_0.csv
2020-12-31 13:23:36,843 [INFO] kashgari - Epoch 8: f1-score did not improve from 0.00000



                precision    recall  f1-score   support

      location     0.0000    0.0000    0.0000        53
          time     0.0000    0.0000    0.0000       450
       contact     0.0000    0.0000    0.0000        13
      med_exam     0.0000    0.0000    0.0000        84
         money     0.0000    0.0000    0.0000        11
          name     0.0000    0.0000    0.0000        43
        family     0.0000    0.0000    0.0000        11
    profession     0.0000    0.0000    0.0000        11
clinical_event     0.0000    0.0000    0.0000         2
     education     0.0000    0.0000    0.0000         1

     micro avg     0.0000    0.0000    0.0000       679
     macro avg     0.0000    0.0000    0.0000       679

epoch: 7 precision: 0.000000, recall: 0.000000, f1-score: 0.000000
Epoch 9/10
5/5 [==============================] - 41s 8s/step - loss: 50.4247 - accuracy: 0.9697 - val_loss: 1026.0139 - val_accuracy: 0.9781


2020-12-31 13:24:17,805 [DEBUG] kashgari - predict seq_length: None, input: (2, 200, 512)




13/13 [==============================] - 12s 946ms/step


2020-12-31 13:24:30,201 [DEBUG] kashgari - predict output: (200, 512)
2020-12-31 13:24:30,202 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 2 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:24:30,859 [INFO] kashgari - Successfully recorded this epoch into model///history/history_0.csv
2020-12-31 13:24:30,860 [INFO] kashgari - Epoch 9: f1-score improved from 0.00000 to 0.02054, saving model to model//



                precision    recall  f1-score   support

      location     0.0000    0.0000    0.0000        53
          time     0.0423    0.0244    0.0310       450
       contact     0.0000    0.0000    0.0000        13
      med_exam     0.0000    0.0000    0.0000        84
         money     0.0000    0.0000    0.0000        11
          name     0.0000    0.0000    0.0000        43
        family     0.0000    0.0000    0.0000        11
    profession     0.0000    0.0000    0.0000        11
clinical_event     0.0000    0.0000    0.0000         2
     education     0.0000    0.0000    0.0000         1

     micro avg     0.0396    0.0162    0.0230       679
     macro avg     0.0280    0.0162    0.0205       679

epoch: 8 precision: 0.028039, recall: 0.016200, f1-score: 0.020536


2020-12-31 13:24:35,016 [INFO] kashgari - model saved to /content/drive/My Drive/AICUP2020/model


Epoch 10/10
5/5 [==============================] - 42s 9s/step - loss: 47.3154 - accuracy: 0.9712 - val_loss: 1041.6743 - val_accuracy: 0.9788


2020-12-31 13:25:16,697 [DEBUG] kashgari - predict seq_length: None, input: (2, 200, 512)




13/13 [==============================] - 12s 945ms/step


2020-12-31 13:25:29,171 [DEBUG] kashgari - predict output: (200, 512)
2020-12-31 13:25:29,172 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 2 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:25:29,844 [INFO] kashgari - Successfully recorded this epoch into model///history/history_0.csv
2020-12-31 13:25:29,845 [INFO] kashgari - Epoch 10: f1-score improved from 0.02054 to 0.03365, saving model to model//



                precision    recall  f1-score   support

      location     0.0000    0.0000    0.0000        53
          time     0.0695    0.0400    0.0508       450
       contact     0.0000    0.0000    0.0000        13
      med_exam     0.0000    0.0000    0.0000        84
         money     0.0000    0.0000    0.0000        11
          name     0.0000    0.0000    0.0000        43
        family     0.0000    0.0000    0.0000        11
    profession     0.0000    0.0000    0.0000        11
clinical_event     0.0000    0.0000    0.0000         2
     education     0.0000    0.0000    0.0000         1

     micro avg     0.0641    0.0265    0.0375       679
     macro avg     0.0461    0.0265    0.0337       679

epoch: 9 precision: 0.046059, recall: 0.026510, f1-score: 0.033651


2020-12-31 13:25:34,008 [INFO] kashgari - model saved to /content/drive/My Drive/AICUP2020/model


# Check Performation

In [13]:
perf = pd.read_csv(f'{MODEL_SAVE_DIR}/history/history_0.csv')
perf

loss  accuracy     val_loss  ...  precision   recall  f1-score
0  424.972260  0.764347  1019.935730  ...   0.000000  0.00000  0.000000
1  125.410912  0.966130  1009.375854  ...   0.000000  0.00000  0.000000
2   92.806396  0.966618  1038.002197  ...   0.000000  0.00000  0.000000
3   71.716629  0.968056  1047.966187  ...   0.000000  0.00000  0.000000
4   71.438614  0.966241  1007.644165  ...   0.000000  0.00000  0.000000
5   66.619026  0.966628  1024.445312  ...   0.000000  0.00000  0.000000
6   59.601776  0.966547  1052.875977  ...   0.000000  0.00000  0.000000
7   52.855679  0.968626  1023.481201  ...   0.000000  0.00000  0.000000
8   50.165981  0.969803  1026.013916  ...   0.028039  0.01620  0.020536
9   46.823929  0.970348  1041.674316  ...   0.046059  0.02651  0.033651

[10 rows x 7 columns]

In [14]:
fig = make_subplots(rows=2, cols=2,
           specs=[[{}, {}], [{'colspan': 2}, None]],
           subplot_titles=('Loss and Validate loss', 'Accuracy and Validate accuracy', 'F1 Score'))
fig.add_trace(go.Scatter(y=perf['loss'], name='loss'), row=1, col=1)
fig.add_trace(go.Scatter(y=perf['val_loss'], name='validate loss'), row=1, col=1)

fig.add_trace(go.Scatter(y=perf['accuracy'], name='accuracy'), row=1, col=2)
fig.add_trace(go.Scatter(y=perf['val_accuracy'], name='validate accuracy'), row=1, col=2)

for prop in perf.columns[4:]:
  fig.add_trace(go.Scatter(y=perf[prop], name=prop), row=2, col=1)

fig.update_layout(height=800, width=1000)

fig.show()

# Prediction

In [15]:
for_predict = load_test_file('./data/1214test.txt')

In [16]:
def predict(model: tf.keras.Model, for_predict):
    output_df = pd.DataFrame()
    for article_id in range(len(for_predict)):
      tokenized_text = list(for_predict[article_id])
      batched_text = split_chunks(tokenized_text)
      batched_labels = model.predict(batched_text)
      labels = [l for batch in batched_labels for l in batch]

      entities_result = format_result(tokenized_text, labels)
      df = pd.DataFrame(entities_result)
      df.insert(0, 'article_id', [article_id for _ in range(len(entities_result))])
      output_df = pd.concat([output_df, df], ignore_index=True)
    
    return output_df

In [17]:
ans = predict(model, for_predict)
ans[['article_id', 'start_position', 'end_position']] = ans[['article_id', 'start_position', 'end_position']].astype(int)

2020-12-31 13:25:51,433 [DEBUG] kashgari - predict seq_length: None, input: (2, 1, 509)


1/1 [==============================] - 5s 5s/step


2020-12-31 13:25:56,603 [DEBUG] kashgari - predict output: (1, 509)
2020-12-31 13:25:56,607 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 

1/1 [==============================] - 1s 559ms/step


2020-12-31 13:25:57,212 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:25:57,212 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:25:57,230 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 472ms/step


2020-12-31 13:25:57,734 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:25:57,735 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:25:57,750 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 392ms/step


2020-12-31 13:25:58,172 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:25:58,173 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:25:58,190 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 380ms/step


2020-12-31 13:25:58,601 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:25:58,603 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:25:58,625 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 510ms/step


2020-12-31 13:25:59,165 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:25:59,166 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:25:59,189 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 514ms/step


2020-12-31 13:25:59,737 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:25:59,738 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:25:59,757 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 430ms/step


2020-12-31 13:26:00,217 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:00,219 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:00,235 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 447ms/step


2020-12-31 13:26:00,714 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:00,715 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:00,739 [DEBUG] kashgari - predict seq_length: None, input: (2, 7, 512)


1/1 [==============================] - 1s 587ms/step


2020-12-31 13:26:01,356 [DEBUG] kashgari - predict output: (7, 512)
2020-12-31 13:26:01,357 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 2 2 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:01,378 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 470ms/step


2020-12-31 13:26:01,876 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:01,879 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:01,913 [DEBUG] kashgari - predict seq_length: None, input: (2, 13, 512)


1/1 [==============================] - 1s 836ms/step


2020-12-31 13:26:02,788 [DEBUG] kashgari - predict output: (13, 512)
2020-12-31 13:26:02,789 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:02,813 [DEBUG] kashgari - predict seq_length: None, input: (2, 1, 302)


1/1 [==============================] - 5s 5s/step


2020-12-31 13:26:07,553 [DEBUG] kashgari - predict output: (1, 302)
2020-12-31 13:26:07,554 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
2020-12-31 13:26:07,571 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 1s 504ms/step


2020-12-31 13:26:08,112 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:08,113 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:08,131 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 429ms/step


2020-12-31 13:26:08,593 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:08,594 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:08,611 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 487ms/step


2020-12-31 13:26:09,129 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:09,130 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:09,147 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 418ms/step


2020-12-31 13:26:09,597 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:09,597 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:09,614 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 381ms/step


2020-12-31 13:26:10,026 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:10,026 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:10,047 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 468ms/step


2020-12-31 13:26:10,550 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:10,551 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:10,572 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 1s 555ms/step


2020-12-31 13:26:11,155 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:11,157 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:11,177 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 416ms/step


2020-12-31 13:26:11,626 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:11,627 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 2 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:11,643 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 429ms/step


2020-12-31 13:26:12,101 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:12,102 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:12,117 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 378ms/step


2020-12-31 13:26:12,523 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:12,526 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:12,548 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 541ms/step


2020-12-31 13:26:13,119 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:26:13,120 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:13,135 [DEBUG] kashgari - predict seq_length: None, input: (2, 1, 503)


1/1 [==============================] - 0s 339ms/step


2020-12-31 13:26:13,502 [DEBUG] kashgari - predict output: (1, 503)
2020-12-31 13:26:13,504 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 2 1 1 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 

1/1 [==============================] - 0s 402ms/step


2020-12-31 13:26:13,950 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:13,952 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:13,970 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 462ms/step


2020-12-31 13:26:14,463 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:14,464 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:14,481 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 428ms/step


2020-12-31 13:26:14,939 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:14,940 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:14,960 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 465ms/step


2020-12-31 13:26:15,456 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:15,458 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:15,473 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 383ms/step


2020-12-31 13:26:15,886 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:15,887 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:15,904 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 437ms/step


2020-12-31 13:26:16,372 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:16,378 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:16,398 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 474ms/step


2020-12-31 13:26:16,903 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:16,904 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:16,923 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 425ms/step


2020-12-31 13:26:17,379 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:17,380 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:17,396 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 378ms/step


2020-12-31 13:26:17,807 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:17,809 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:17,823 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 397ms/step


2020-12-31 13:26:18,247 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:18,249 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:18,267 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 467ms/step


2020-12-31 13:26:18,765 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:18,766 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:18,786 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 428ms/step


2020-12-31 13:26:19,245 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:19,246 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:19,260 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 391ms/step


2020-12-31 13:26:19,685 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:19,685 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:19,699 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 424ms/step


2020-12-31 13:26:20,152 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:20,153 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:20,174 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 1s 507ms/step


2020-12-31 13:26:20,715 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:20,716 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:20,734 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 459ms/step


2020-12-31 13:26:21,224 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:21,225 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:21,249 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 512)


1/1 [==============================] - 1s 644ms/step


2020-12-31 13:26:21,923 [DEBUG] kashgari - predict output: (6, 512)
2020-12-31 13:26:21,925 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:21,947 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 479ms/step


2020-12-31 13:26:22,459 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:22,459 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:22,478 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 376ms/step


2020-12-31 13:26:22,884 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:22,885 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
2020-12-31 13:26:22,901 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 449ms/step


2020-12-31 13:26:23,379 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:23,380 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:23,406 [DEBUG] kashgari - predict seq_length: None, input: (2, 7, 512)


1/1 [==============================] - 1s 649ms/step


2020-12-31 13:26:24,085 [DEBUG] kashgari - predict output: (7, 512)
2020-12-31 13:26:24,086 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:24,104 [DEBUG] kashgari - predict seq_length: None, input: (2, 1, 407)


1/1 [==============================] - 0s 285ms/step


2020-12-31 13:26:24,418 [DEBUG] kashgari - predict output: (1, 407)
2020-12-31 13:26:24,420 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1]]
2020-12-31 13:26:24,435 [D

1/1 [==============================] - 0s 496ms/step


2020-12-31 13:26:24,961 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:24,962 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
2020-12-31 13:26:24,982 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 498ms/step


2020-12-31 13:26:25,514 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:25,515 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:25,537 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 437ms/step


2020-12-31 13:26:26,004 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:26,005 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:26,026 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 537ms/step


2020-12-31 13:26:26,593 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:26:26,594 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:26,617 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 521ms/step


2020-12-31 13:26:27,170 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:26:27,171 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:27,187 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 390ms/step


2020-12-31 13:26:27,606 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:27,607 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:27,629 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 516ms/step


2020-12-31 13:26:28,179 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:26:28,180 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:28,198 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 428ms/step


2020-12-31 13:26:28,656 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:28,657 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:28,676 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 423ms/step


2020-12-31 13:26:29,136 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:29,137 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:29,155 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 448ms/step


2020-12-31 13:26:29,632 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:29,633 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:29,650 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 395ms/step


2020-12-31 13:26:30,075 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:30,076 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:30,097 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 470ms/step


2020-12-31 13:26:30,597 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:30,598 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:30,616 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 1s 514ms/step


2020-12-31 13:26:31,161 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:31,162 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:31,192 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 515ms/step


2020-12-31 13:26:31,739 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:26:31,740 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:31,760 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 496ms/step


2020-12-31 13:26:32,287 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:32,287 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:32,312 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 494ms/step


2020-12-31 13:26:32,834 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:32,836 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:32,853 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 431ms/step


2020-12-31 13:26:33,316 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:33,324 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 2 ... 1 1 1]]
2020-12-31 13:26:33,346 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 396ms/step


2020-12-31 13:26:33,772 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:33,773 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:33,794 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 546ms/step


2020-12-31 13:26:34,370 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:26:34,370 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:34,390 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 414ms/step


2020-12-31 13:26:34,835 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:34,836 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:34,862 [DEBUG] kashgari - predict seq_length: None, input: (2, 8, 512)


1/1 [==============================] - 1s 635ms/step


2020-12-31 13:26:35,528 [DEBUG] kashgari - predict output: (8, 512)
2020-12-31 13:26:35,529 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:35,554 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 542ms/step


2020-12-31 13:26:36,127 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:26:36,128 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:36,149 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 419ms/step


2020-12-31 13:26:36,602 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:36,603 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:36,624 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 511ms/step


2020-12-31 13:26:37,168 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:26:37,169 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:37,187 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 422ms/step


2020-12-31 13:26:37,637 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:37,638 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:37,657 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 452ms/step


2020-12-31 13:26:38,140 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:38,140 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:38,161 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 480ms/step


2020-12-31 13:26:38,673 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:38,674 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:38,693 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 434ms/step


2020-12-31 13:26:39,154 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:39,156 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:39,174 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 475ms/step


2020-12-31 13:26:39,679 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:39,680 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:39,706 [DEBUG] kashgari - predict seq_length: None, input: (2, 8, 512)


1/1 [==============================] - 1s 657ms/step


2020-12-31 13:26:40,393 [DEBUG] kashgari - predict output: (8, 512)
2020-12-31 13:26:40,394 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:40,425 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 518ms/step


2020-12-31 13:26:40,973 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:26:40,975 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:40,991 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 379ms/step


2020-12-31 13:26:41,401 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:41,402 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:41,428 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 512)


1/1 [==============================] - 1s 588ms/step


2020-12-31 13:26:42,048 [DEBUG] kashgari - predict output: (6, 512)
2020-12-31 13:26:42,049 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
2020-12-31 13:26:42,070 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 457ms/step


2020-12-31 13:26:42,557 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:42,559 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:42,578 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 480ms/step


2020-12-31 13:26:43,089 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:43,090 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:43,111 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 464ms/step


2020-12-31 13:26:43,606 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:43,606 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:43,633 [DEBUG] kashgari - predict seq_length: None, input: (2, 8, 512)


1/1 [==============================] - 1s 650ms/step


2020-12-31 13:26:44,318 [DEBUG] kashgari - predict output: (8, 512)
2020-12-31 13:26:44,319 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:44,346 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 514ms/step


2020-12-31 13:26:44,892 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:26:44,893 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:44,918 [DEBUG] kashgari - predict seq_length: None, input: (2, 7, 512)


1/1 [==============================] - 1s 601ms/step


2020-12-31 13:26:45,549 [DEBUG] kashgari - predict output: (7, 512)
2020-12-31 13:26:45,550 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:45,569 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 453ms/step


2020-12-31 13:26:46,053 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:46,054 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:46,070 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 385ms/step


2020-12-31 13:26:46,486 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:46,486 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:46,507 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 520ms/step


2020-12-31 13:26:47,058 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:26:47,059 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:47,079 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 419ms/step


2020-12-31 13:26:47,528 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:47,529 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:47,547 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 464ms/step


2020-12-31 13:26:48,042 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:48,043 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 2 2]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:48,061 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 430ms/step


2020-12-31 13:26:48,522 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:48,523 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:48,542 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 1s 550ms/step


2020-12-31 13:26:49,126 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:49,127 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:49,144 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 411ms/step


2020-12-31 13:26:49,585 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:49,586 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:49,609 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 582ms/step


2020-12-31 13:26:50,222 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:26:50,222 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:50,243 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 498ms/step


2020-12-31 13:26:50,771 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:50,772 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:50,797 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 515ms/step


2020-12-31 13:26:51,341 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:26:51,344 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:51,367 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 512)


1/1 [==============================] - 1s 571ms/step


2020-12-31 13:26:51,972 [DEBUG] kashgari - predict output: (6, 512)
2020-12-31 13:26:51,974 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:51,994 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 1s 532ms/step


2020-12-31 13:26:52,561 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:26:52,562 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:52,583 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 1s 584ms/step


2020-12-31 13:26:53,201 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:53,202 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:53,223 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 539ms/step


2020-12-31 13:26:53,794 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:26:53,795 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:53,814 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 380ms/step


2020-12-31 13:26:54,227 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:54,228 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:54,243 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 497ms/step


2020-12-31 13:26:54,773 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:54,774 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:54,790 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 458ms/step


2020-12-31 13:26:55,279 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:55,280 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:55,293 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 383ms/step


2020-12-31 13:26:55,711 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:55,712 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:55,727 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 395ms/step


2020-12-31 13:26:56,154 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:56,155 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:56,170 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 390ms/step


2020-12-31 13:26:56,588 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:26:56,589 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 2 ... 1 1 1]]
2020-12-31 13:26:56,620 [DEBUG] kashgari - predict seq_length: None, input: (2, 7, 512)


1/1 [==============================] - 1s 651ms/step


2020-12-31 13:26:57,303 [DEBUG] kashgari - predict output: (7, 512)
2020-12-31 13:26:57,304 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:57,332 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 512)


1/1 [==============================] - 1s 579ms/step


2020-12-31 13:26:57,943 [DEBUG] kashgari - predict output: (6, 512)
2020-12-31 13:26:57,943 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:57,965 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 494ms/step


2020-12-31 13:26:58,491 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:58,491 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:26:58,514 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 1s 500ms/step


2020-12-31 13:26:59,046 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:26:59,047 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:59,077 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 512)


1/1 [==============================] - 1s 684ms/step


2020-12-31 13:26:59,796 [DEBUG] kashgari - predict output: (6, 512)
2020-12-31 13:26:59,797 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:26:59,816 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 407ms/step


2020-12-31 13:27:00,257 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:27:00,257 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:00,277 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 487ms/step


2020-12-31 13:27:00,794 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:27:00,795 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:00,818 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 512)


1/1 [==============================] - 1s 583ms/step


2020-12-31 13:27:01,430 [DEBUG] kashgari - predict output: (6, 512)
2020-12-31 13:27:01,431 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:01,457 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 512)


1/1 [==============================] - 1s 587ms/step


2020-12-31 13:27:02,076 [DEBUG] kashgari - predict output: (6, 512)
2020-12-31 13:27:02,076 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:02,097 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 450ms/step


2020-12-31 13:27:02,575 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:27:02,576 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:02,592 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 426ms/step


2020-12-31 13:27:03,049 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:27:03,049 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 2 2 2]
 [1 1 2 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:03,069 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 473ms/step


2020-12-31 13:27:03,578 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:27:03,581 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:03,595 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 378ms/step


2020-12-31 13:27:04,001 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:27:04,002 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:04,029 [DEBUG] kashgari - predict seq_length: None, input: (2, 8, 512)


1/1 [==============================] - 1s 655ms/step


2020-12-31 13:27:04,723 [DEBUG] kashgari - predict output: (8, 512)
2020-12-31 13:27:04,725 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:04,746 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 384ms/step


2020-12-31 13:27:05,159 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:27:05,160 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:05,179 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 479ms/step


2020-12-31 13:27:05,686 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:27:05,687 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 2 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:05,710 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 443ms/step


2020-12-31 13:27:06,183 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:27:06,184 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:06,198 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 376ms/step


2020-12-31 13:27:06,605 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:27:06,606 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:06,621 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 396ms/step


2020-12-31 13:27:07,045 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:27:07,047 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:07,061 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 379ms/step


2020-12-31 13:27:07,469 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:27:07,470 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:07,484 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 393ms/step


2020-12-31 13:27:07,907 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:27:07,907 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:07,923 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 378ms/step


2020-12-31 13:27:08,332 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:27:08,333 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:08,354 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 515ms/step


2020-12-31 13:27:08,902 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:27:08,903 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:08,920 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 448ms/step


2020-12-31 13:27:09,400 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:27:09,402 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:09,417 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 435ms/step


2020-12-31 13:27:09,883 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:27:09,883 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 2 2 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:09,902 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 466ms/step


2020-12-31 13:27:10,400 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:27:10,401 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:10,420 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 441ms/step


2020-12-31 13:27:10,890 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:27:10,891 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:10,905 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 387ms/step


2020-12-31 13:27:11,321 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:27:11,321 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:11,340 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 448ms/step


2020-12-31 13:27:11,820 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:27:11,820 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:11,836 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 416ms/step


2020-12-31 13:27:12,284 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:27:12,285 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:12,305 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 608ms/step


2020-12-31 13:27:12,948 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:27:12,949 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:12,973 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 1s 539ms/step


2020-12-31 13:27:13,546 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:27:13,547 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:13,951 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 385ms/step


2020-12-31 13:27:14,368 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:27:14,369 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:14,388 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 469ms/step


2020-12-31 13:27:14,886 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:27:14,888 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:14,912 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 536ms/step


2020-12-31 13:27:15,479 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:27:15,480 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:15,502 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 512)


1/1 [==============================] - 1s 578ms/step


2020-12-31 13:27:16,112 [DEBUG] kashgari - predict output: (6, 512)
2020-12-31 13:27:16,113 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:16,132 [DEBUG] kashgari - predict seq_length: None, input: (2, 2, 512)


1/1 [==============================] - 0s 377ms/step


2020-12-31 13:27:16,539 [DEBUG] kashgari - predict output: (2, 512)
2020-12-31 13:27:16,540 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:16,560 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 512ms/step


2020-12-31 13:27:17,103 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:27:17,104 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:17,126 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 463ms/step


2020-12-31 13:27:17,619 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:27:17,619 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:17,638 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 458ms/step


2020-12-31 13:27:18,127 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:27:18,128 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:18,149 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 468ms/step


2020-12-31 13:27:18,648 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:27:18,649 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:18,667 [DEBUG] kashgari - predict seq_length: None, input: (2, 3, 512)


1/1 [==============================] - 0s 491ms/step


2020-12-31 13:27:19,188 [DEBUG] kashgari - predict output: (3, 512)
2020-12-31 13:27:19,190 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:19,211 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 596ms/step


2020-12-31 13:27:19,839 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:27:19,840 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:19,888 [DEBUG] kashgari - predict seq_length: None, input: (2, 15, 512)


1/1 [==============================] - 1s 936ms/step


2020-12-31 13:27:20,860 [DEBUG] kashgari - predict output: (15, 512)
2020-12-31 13:27:20,861 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:20,896 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 0s 470ms/step


2020-12-31 13:27:21,400 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:27:21,401 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:21,429 [DEBUG] kashgari - predict seq_length: None, input: (2, 8, 512)


1/1 [==============================] - 1s 638ms/step


2020-12-31 13:27:22,097 [DEBUG] kashgari - predict output: (8, 512)
2020-12-31 13:27:22,097 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
2020-12-31 13:27:22,124 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 512)


1/1 [==============================] - 1s 576ms/step


2020-12-31 13:27:22,730 [DEBUG] kashgari - predict output: (6, 512)
2020-12-31 13:27:22,731 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:22,753 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 512)


1/1 [==============================] - 1s 528ms/step


2020-12-31 13:27:23,313 [DEBUG] kashgari - predict output: (5, 512)
2020-12-31 13:27:23,314 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:23,336 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 512)


1/1 [==============================] - 1s 557ms/step


2020-12-31 13:27:23,930 [DEBUG] kashgari - predict output: (6, 512)
2020-12-31 13:27:23,931 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:23,963 [DEBUG] kashgari - predict seq_length: None, input: (2, 7, 512)


1/1 [==============================] - 1s 683ms/step


2020-12-31 13:27:24,677 [DEBUG] kashgari - predict output: (7, 512)
2020-12-31 13:27:24,679 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
2020-12-31 13:27:24,711 [DEBUG] kashgari - predict seq_length: None, input: (2, 8, 512)


1/1 [==============================] - 1s 724ms/step


2020-12-31 13:27:25,469 [DEBUG] kashgari - predict output: (8, 512)
2020-12-31 13:27:25,470 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]]
2020-12-31 13:27:25,495 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 512)


1/1 [==============================] - 1s 543ms/step


2020-12-31 13:27:26,070 [DEBUG] kashgari - predict output: (4, 512)
2020-12-31 13:27:26,074 [DEBUG] kashgari - predict output argmax: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]


In [18]:
ans

article_id  start_position  end_position entity_text entity_type
0            4             365           368         三個禮        time
1            5            1490          1493         下個月        time
2            6            1468          1471         兩個月        time
3           11            5824          5827         一個月        time
4           15             708           712        兩個禮拜        time
5           17             625           628         三個月        time
6           27            1039          1043        三個禮拜        time
7           38             662           666        一個禮拜        time
8           48             835           838         三個月        time
9           48            1596          1599         三個月        time
10          48            1609          1612         一個月        time
11          55             749           752         一個月        time
12          55            1197          1200         三個月        time
13          56            1360          1364        三個禮拜        time
14          57             584           587         七月初        time
15          72             989           993        一個禮拜        time
16          78             552           556        三個禮拜        time
17          84            2092          2094          一個        time
18          92            1757          1761        兩個禮拜        time
19          94            2227          2230         五個月        time
20          99            1888          1891         三個月        time
21         100            2243          2247        四個禮拜        time
22         102             828           832        兩個禮拜        time
23         137            1901          1905        一個禮拜        time
24         147            1654          1657         三個月        time
25         150            3061          3066       一個月兩到        time
26         153            2693          2696         三個月        time
27         157            3670          3672          一天        time

In [ ]:
ans.to_csv(f'./output/output.tsv', sep='\t', index=False)